var ZetaNative = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var b=moduleArg,d,l,p=new Promise((a,c)=>{d=a;l=c}),q=Object.assign({},b),r="",u;"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src);_scriptName&&(r=_scriptName);r.startsWith("blob:")?r="":r=r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1);u=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var v=console.log.bind(console),w=console.error.bind(console);Object.assign(b,q);q=null;
var x,y=!1,D,E,F=a=>a.startsWith("data:application/octet-stream;base64,");function G(){var a=x.buffer;new Int8Array(a);new Int16Array(a);b.HEAPU8=D=new Uint8Array(a);new Uint16Array(a);new Int32Array(a);b.HEAPU32=E=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}var H=[],I=[],J=[],K=0,L=null,M;async function N(a){try{var c=await u(a);return new Uint8Array(c)}catch{}throw"both async and sync fetching of the wasm failed";}
async function O(a,c){try{var e=await N(a);return await WebAssembly.instantiate(e,c)}catch(f){throw w(`failed to asynchronously prepare wasm: ${f}`),a=f,a="Aborted("+a+")",w(a),y=!0,a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info."),l(a),a;}}
async function R(a){var c=M;if("function"==typeof WebAssembly.instantiateStreaming&&!F(c))try{var e=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(e,a)}catch(f){w(`wasm streaming compile failed: ${f}`),w("falling back to ArrayBuffer instantiation")}return O(c,a)}
var S=[null,[],[]],T="undefined"!=typeof TextDecoder?new TextDecoder:void 0,U=a=>{for(var c="";;){var e=D[a++];if(!e)return c;c+=String.fromCharCode(e)}},V={d:function(a){console.log(U(a))},m:a=>{var c=D.length;a>>>=0;if(2147483648<a)return!1;for(var e=1;4>=e;e*=2){var f=c*(1+.2/e);f=Math.min(f,a+100663296);a:{f=(Math.min(2147483648,65536*Math.ceil(Math.max(a,f)/65536))-x.buffer.byteLength+65535)/65536|0;try{x.grow(f);G();var t=1;break a}catch(z){}t=void 0}if(t)return!0}return!1},o:()=>52,n:function(){return 70},
i:(a,c,e,f)=>{for(var t=0,z=0;z<e;z++){var X=E[c>>2],P=E[c+4>>2];c+=8;for(var A=0;A<P;A++){var g=D[X+A],B=S[a];if(0===g||10===g){g=B;for(var k=0,m=k+NaN,n=k;g[n]&&!(n>=m);)++n;if(16<n-k&&g.buffer&&T)g=T.decode(g.subarray(k,n));else{for(m="";k<n;){var h=g[k++];if(h&128){var C=g[k++]&63;if(192==(h&224))m+=String.fromCharCode((h&31)<<6|C);else{var Q=g[k++]&63;h=224==(h&240)?(h&15)<<12|C<<6|Q:(h&7)<<18|C<<12|Q<<6|g[k++]&63;65536>h?m+=String.fromCharCode(h):(h-=65536,m+=String.fromCharCode(55296|h>>10,
56320|h&1023))}}else m+=String.fromCharCode(h)}g=m}(1===a?v:w)(g);B.length=0}else B.push(g)}t+=P}E[f>>2]=t;return 0},g:function(a){speakerg_off(a)},l:function(a,c){speakerg_on(a,c)},u:function(a){return vfsg_chdir(a)},v:function(a){return vfsg_close(a)},q:function(a,c,e){return vfsg_findfirst(a,c,e)},p:function(a){return vfsg_findnext(a)},t:function(a,c){return vfsg_getcwd(a,c)},j:function(a,c){return vfsg_open(a,c)},a:function(a,c,e){return vfsg_read(a,c,e)},c:function(a,c,e){return vfsg_seek(a,
c,e)},s:function(a,c){return vfsg_truncate(a,c)},r:function(a,c,e){return vfsg_write(a,c,e)},h:function(a){return vfsg_has_feature(a)},k:function(){return vfsg_time_ms()},b:function(a){return zetag_update_blink(a)},e:function(a,c,e){return zetag_update_charset(a,c,e)},f:function(a){return zetag_update_palette(a)}},W;
(async function(){K++;var a={a:V};M??=F("zeta_native.wasm")?"zeta_native.wasm":r+"zeta_native.wasm";try{return W=(await R(a)).instance.exports,x=W.w,G(),I.unshift(W.x),K--,0==K&&L&&(a=L,L=null,a()),W}catch(c){return l(c),Promise.reject(c)}})();b._zzt_get_ip=()=>(b._zzt_get_ip=W.z)();b._zzt_get_cycles=()=>(b._zzt_get_cycles=W.A)();b._zzt_kmod_get=()=>(b._zzt_kmod_get=W.B)();b._zzt_kmod_set=a=>(b._zzt_kmod_set=W.C)(a);b._zzt_kmod_clear=a=>(b._zzt_kmod_clear=W.D)(a);
b._zzt_set_lock_charset=a=>(b._zzt_set_lock_charset=W.E)(a);b._zzt_set_lock_palette=a=>(b._zzt_set_lock_palette=W.F)(a);b._zzt_key_get_delay=()=>(b._zzt_key_get_delay=W.G)();b._zzt_key_get_repeat_delay=()=>(b._zzt_key_get_repeat_delay=W.H)();b._zzt_key_set_delay=(a,c)=>(b._zzt_key_set_delay=W.I)(a,c);b._zzt_key=(a,c)=>(b._zzt_key=W.J)(a,c);b._zzt_keyup=a=>(b._zzt_keyup=W.K)(a);b._zzt_mark_frame=()=>(b._zzt_mark_frame=W.L)();b._zzt_joy_set=a=>(b._zzt_joy_set=W.M)(a);
b._zzt_joy_clear=a=>(b._zzt_joy_clear=W.N)(a);b._zzt_joy_axis=(a,c)=>(b._zzt_joy_axis=W.O)(a,c);b._zzt_mouse_set=a=>(b._zzt_mouse_set=W.P)(a);b._zzt_mouse_clear=a=>(b._zzt_mouse_clear=W.Q)(a);b._zzt_mouse_axis=(a,c)=>(b._zzt_mouse_axis=W.R)(a,c);b._zzt_get_charset_default=()=>(b._zzt_get_charset_default=W.S)();b._zzt_force_default_charset=a=>(b._zzt_force_default_charset=W.T)(a);b._zzt_load_charset=(a,c,e,f)=>(b._zzt_load_charset=W.U)(a,c,e,f);b._zzt_set_timer_offset=a=>(b._zzt_set_timer_offset=W.V)(a);
b._zzt_set_max_extended_memory=a=>(b._zzt_set_max_extended_memory=W.W)(a);b._zzt_video_mode=()=>(b._zzt_video_mode=W.X)();b._zzt_load_palette_default=()=>(b._zzt_load_palette_default=W.Y)();b._zzt_key_pop=a=>(b._zzt_key_pop=W.Z)(a);b._zzt_load_binary=(a,c)=>(b._zzt_load_binary=W._)(a,c);b._zzt_load_ega_palette=a=>(b._zzt_load_ega_palette=W.$)(a);b._zzt_load_palette=a=>(b._zzt_load_palette=W.aa)(a);b._zzt_load_blink=a=>(b._zzt_load_blink=W.ba)(a);
b._zzt_get_active_blink_duration_ms=()=>(b._zzt_get_active_blink_duration_ms=W.ca)();b._zzt_get_screen_size=(a,c)=>(b._zzt_get_screen_size=W.da)(a,c);b._zzt_get_charset=(a,c)=>(b._zzt_get_charset=W.ea)(a,c);b._zzt_get_palette=()=>(b._zzt_get_palette=W.fa)();b._zzt_get_blink=()=>(b._zzt_get_blink=W.ga)();b._zzt_get_blink_user_override=()=>(b._zzt_get_blink_user_override=W.ha)();b._zzt_set_blink_user_override=a=>(b._zzt_set_blink_user_override=W.ia)(a);
b._zzt_get_blink_duration_ms=()=>(b._zzt_get_blink_duration_ms=W.ja)();b._zzt_set_blink_duration_ms=a=>(b._zzt_set_blink_duration_ms=W.ka)(a);b._zzt_init=a=>(b._zzt_init=W.la)(a);b._audio_set_remove_player_movement_sound=a=>(b._audio_set_remove_player_movement_sound=W.ma)(a);b._zzt_execute=a=>(b._zzt_execute=W.na)(a);b._zzt_mark_timer=()=>(b._zzt_mark_timer=W.oa)();b._zzt_mark_timer_turbo=()=>(b._zzt_mark_timer_turbo=W.pa)();b._zzt_get_ram=()=>(b._zzt_get_ram=W.qa)();b._malloc=a=>(b._malloc=W.ra)(a);
b._free=a=>(b._free=W.sa)(a);b._ui_activate=()=>(b._ui_activate=W.ta)();b._audio_stream_get_volume=()=>(b._audio_stream_get_volume=W.ua)();b._audio_get_remove_player_movement_sound=()=>(b._audio_get_remove_player_movement_sound=W.va)();b._audio_stream_set_volume=a=>(b._audio_stream_set_volume=W.wa)(a);b._audio_stream_init=(a,c,e,f)=>(b._audio_stream_init=W.xa)(a,c,e,f);b._audio_stream_get_max_volume=()=>(b._audio_stream_get_max_volume=W.ya)();
b._audio_stream_generate=(a,c,e)=>(b._audio_stream_generate=W.za)(a,c,e);b._audio_stream_append_on=(a,c,e)=>(b._audio_stream_append_on=W.Aa)(a,c,e);b._audio_local_delay_time=(a,c,e)=>(b._audio_local_delay_time=W.Ba)(a,c,e);b._audio_should_insert_pause=(a,c)=>(b._audio_should_insert_pause=W.Ca)(a,c);b._audio_stream_append_off=(a,c)=>(b._audio_stream_append_off=W.Da)(a,c);b._audio_generate_init=()=>(b._audio_generate_init=W.Ea)();b._audio_get_note_delay=()=>(b._audio_get_note_delay=W.Fa)();
b._audio_set_note_delay=a=>(b._audio_set_note_delay=W.Ga)(a);b.AsciiToString=U;function Y(){if(0<K)L=Y;else{for(;0<H.length;)H.shift()(b);if(0<K)L=Y;else if(b.calledRun=!0,!y){for(;0<I.length;)I.shift()(b);for(d(b);0<J.length;)J.shift()(b)}}}Y();moduleRtn=p;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = ZetaNative;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = ZetaNative;
} else if (typeof define === 'function' && define['amd'])
  define([], () => ZetaNative);
