
var ZetaNative = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(ZetaNative) {
  ZetaNative = ZetaNative || {};


null;var a;a||(a=typeof ZetaNative !== 'undefined' ? ZetaNative : {});var l,m;a.ready=new Promise(function(b,c){l=b;m=c});var p=Object.assign({},a),r="";"undefined"!==typeof document&&document.currentScript&&(r=document.currentScript.src);_scriptDir&&(r=_scriptDir);0!==r.indexOf("blob:")?r=r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):r="";var aa=a.print||console.log.bind(console),u=a.printErr||console.warn.bind(console);Object.assign(a,p);p=null;var v;a.wasmBinary&&(v=a.wasmBinary);
var noExitRuntime=a.noExitRuntime||!0;"object"!==typeof WebAssembly&&w("no native wasm support detected");var x,y=!1,z="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;function A(b){for(var c="";;){var d=B[b++>>0];if(!d)return c;c+=String.fromCharCode(d)}}var C,B,D;
function E(){var b=x.buffer;C=b;a.HEAP8=new Int8Array(b);a.HEAP16=new Int16Array(b);a.HEAP32=D=new Int32Array(b);a.HEAPU8=B=new Uint8Array(b);a.HEAPU16=new Uint16Array(b);a.HEAPU32=new Uint32Array(b);a.HEAPF32=new Float32Array(b);a.HEAPF64=new Float64Array(b)}var I,J=[],K=[],L=[];function ba(){var b=a.preRun.shift();J.unshift(b)}var M=0,N=null,O=null;a.preloadedImages={};a.preloadedAudios={};
function w(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";u(b);y=!0;b=new WebAssembly.RuntimeError(b+". Build with -s ASSERTIONS=1 for more info.");m(b);throw b;}function P(){return Q.startsWith("data:application/octet-stream;base64,")}var Q;Q="zeta_native.wasm";if(!P()){var R=Q;Q=a.locateFile?a.locateFile(R,r):r+R}function S(){var b=Q;try{if(b==Q&&v)return new Uint8Array(v);throw"both async and sync fetching of the wasm failed";}catch(c){w(c)}}
function ca(){return v||"function"!==typeof fetch?Promise.resolve().then(function(){return S()}):fetch(Q,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+Q+"'";return b.arrayBuffer()}).catch(function(){return S()})}function T(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var d=c.ta;"number"===typeof d?void 0===c.sa?U(d)():U(d)(c.sa):d(void 0===c.sa?null:c.sa)}}}var V=[];
function U(b){var c=V[b];c||(b>=V.length&&(V.length=b+1),V[b]=c=I.get(b));return c}
var da=[null,[],[]],fa={d:function(b){console.log(A(b))},p:function(b,c,d){B.copyWithin(b,c,c+d)},n:function(b){var c=B.length;b>>>=0;if(2147483648<b)return!1;for(var d=1;4>=d;d*=2){var f=c*(1+.2/d);f=Math.min(f,b+100663296);f=Math.max(b,f);0<f%65536&&(f+=65536-f%65536);a:{try{x.grow(Math.min(2147483648,f)-C.byteLength+65535>>>16);E();var e=1;break a}catch(k){}e=void 0}if(e)return!0}return!1},o:function(){return 0},m:function(){},h:function(b,c,d,f){for(var e=0,k=0;k<d;k++){var ea=D[c>>2],Y=D[c+4>>
2];c+=8;for(var F=0;F<Y;F++){var g=B[ea+F],G=da[b];if(0===g||10===g){g=G;for(var n=0,q=n+NaN,t=n;g[t]&&!(t>=q);)++t;if(16<t-n&&g.subarray&&z)g=z.decode(g.subarray(n,t));else{for(q="";n<t;){var h=g[n++];if(h&128){var H=g[n++]&63;if(192==(h&224))q+=String.fromCharCode((h&31)<<6|H);else{var Z=g[n++]&63;h=224==(h&240)?(h&15)<<12|H<<6|Z:(h&7)<<18|H<<12|Z<<6|g[n++]&63;65536>h?q+=String.fromCharCode(h):(h-=65536,q+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else q+=String.fromCharCode(h)}g=q}(1===b?
aa:u)(g);G.length=0}else G.push(g)}e+=Y}D[f>>2]=e;return 0},k:function(b){speakerg_off(b)},l:function(b,c){speakerg_on(b,c)},v:function(b){return vfsg_chdir(b)},w:function(b){return vfsg_close(b)},r:function(b,c,d){return vfsg_findfirst(b,c,d)},q:function(b){return vfsg_findnext(b)},u:function(b,c){return vfsg_getcwd(b,c)},i:function(b,c){return vfsg_open(b,c)},a:function(b,c,d){return vfsg_read(b,c,d)},b:function(b,c,d){return vfsg_seek(b,c,d)},t:function(b,c){return vfsg_truncate(b,c)},s:function(b,
c,d){return vfsg_write(b,c,d)},g:function(b){return vfsg_has_feature(b)},j:function(){return vfsg_time_ms()},f:function(b){return zetag_update_blink(b)},c:function(b,c,d){return zetag_update_charset(b,c,d)},e:function(b){return zetag_update_palette(b)}};
(function(){function b(e){a.asm=e.exports;x=a.asm.x;E();I=a.asm.z;K.unshift(a.asm.y);M--;a.monitorRunDependencies&&a.monitorRunDependencies(M);0==M&&(null!==N&&(clearInterval(N),N=null),O&&(e=O,O=null,e()))}function c(e){b(e.instance)}function d(e){return ca().then(function(k){return WebAssembly.instantiate(k,f)}).then(function(k){return k}).then(e,function(k){u("failed to asynchronously prepare wasm: "+k);w(k)})}var f={a:fa};M++;a.monitorRunDependencies&&a.monitorRunDependencies(M);if(a.instantiateWasm)try{return a.instantiateWasm(f,
b)}catch(e){return u("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return v||"function"!==typeof WebAssembly.instantiateStreaming||P()||"function"!==typeof fetch?d(c):fetch(Q,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,f).then(c,function(k){u("wasm streaming compile failed: "+k);u("falling back to ArrayBuffer instantiation");return d(c)})})})().catch(m);return{}})();
a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.y).apply(null,arguments)};a._zzt_kmod_set=function(){return(a._zzt_kmod_set=a.asm.A).apply(null,arguments)};a._zzt_kmod_clear=function(){return(a._zzt_kmod_clear=a.asm.B).apply(null,arguments)};a._zzt_key_get_delay=function(){return(a._zzt_key_get_delay=a.asm.C).apply(null,arguments)};a._zzt_key_get_repeat_delay=function(){return(a._zzt_key_get_repeat_delay=a.asm.D).apply(null,arguments)};
a._zzt_key_set_delay=function(){return(a._zzt_key_set_delay=a.asm.E).apply(null,arguments)};a._zzt_key=function(){return(a._zzt_key=a.asm.F).apply(null,arguments)};a._zzt_keyup=function(){return(a._zzt_keyup=a.asm.G).apply(null,arguments)};a._zzt_mark_frame=function(){return(a._zzt_mark_frame=a.asm.H).apply(null,arguments)};a._zzt_joy_set=function(){return(a._zzt_joy_set=a.asm.I).apply(null,arguments)};a._zzt_joy_clear=function(){return(a._zzt_joy_clear=a.asm.J).apply(null,arguments)};
a._zzt_joy_axis=function(){return(a._zzt_joy_axis=a.asm.K).apply(null,arguments)};a._zzt_mouse_set=function(){return(a._zzt_mouse_set=a.asm.L).apply(null,arguments)};a._zzt_mouse_clear=function(){return(a._zzt_mouse_clear=a.asm.M).apply(null,arguments)};a._zzt_mouse_axis=function(){return(a._zzt_mouse_axis=a.asm.N).apply(null,arguments)};a._zzt_force_default_charset=function(){return(a._zzt_force_default_charset=a.asm.O).apply(null,arguments)};
a._zzt_load_charset=function(){return(a._zzt_load_charset=a.asm.P).apply(null,arguments)};a._zzt_set_timer_offset=function(){return(a._zzt_set_timer_offset=a.asm.Q).apply(null,arguments)};a._zzt_set_max_extended_memory=function(){return(a._zzt_set_max_extended_memory=a.asm.R).apply(null,arguments)};a._zzt_video_mode=function(){return(a._zzt_video_mode=a.asm.S).apply(null,arguments)};a._zzt_load_binary=function(){return(a._zzt_load_binary=a.asm.T).apply(null,arguments)};
a._zzt_load_ega_palette=function(){return(a._zzt_load_ega_palette=a.asm.U).apply(null,arguments)};a._zzt_load_palette=function(){return(a._zzt_load_palette=a.asm.V).apply(null,arguments)};a._zzt_load_blink=function(){return(a._zzt_load_blink=a.asm.W).apply(null,arguments)};a._zzt_get_screen_size=function(){return(a._zzt_get_screen_size=a.asm.X).apply(null,arguments)};a._zzt_get_charset=function(){return(a._zzt_get_charset=a.asm.Y).apply(null,arguments)};
a._zzt_get_palette=function(){return(a._zzt_get_palette=a.asm.Z).apply(null,arguments)};a._zzt_get_blink=function(){return(a._zzt_get_blink=a.asm._).apply(null,arguments)};a._zzt_init=function(){return(a._zzt_init=a.asm.$).apply(null,arguments)};a._zzt_execute=function(){return(a._zzt_execute=a.asm.aa).apply(null,arguments)};a._zzt_mark_timer=function(){return(a._zzt_mark_timer=a.asm.ba).apply(null,arguments)};
a._zzt_mark_timer_turbo=function(){return(a._zzt_mark_timer_turbo=a.asm.ca).apply(null,arguments)};a._zzt_get_ram=function(){return(a._zzt_get_ram=a.asm.da).apply(null,arguments)};a._malloc=function(){return(a._malloc=a.asm.ea).apply(null,arguments)};a._free=function(){return(a._free=a.asm.fa).apply(null,arguments)};a._audio_stream_init=function(){return(a._audio_stream_init=a.asm.ga).apply(null,arguments)};
a._audio_stream_get_volume=function(){return(a._audio_stream_get_volume=a.asm.ha).apply(null,arguments)};a._audio_stream_get_max_volume=function(){return(a._audio_stream_get_max_volume=a.asm.ia).apply(null,arguments)};a._audio_stream_set_volume=function(){return(a._audio_stream_set_volume=a.asm.ja).apply(null,arguments)};a._audio_stream_generate=function(){return(a._audio_stream_generate=a.asm.ka).apply(null,arguments)};
a._audio_stream_append_on=function(){return(a._audio_stream_append_on=a.asm.la).apply(null,arguments)};a._audio_local_delay_time=function(){return(a._audio_local_delay_time=a.asm.ma).apply(null,arguments)};a._audio_should_insert_pause=function(){return(a._audio_should_insert_pause=a.asm.na).apply(null,arguments)};a._audio_stream_append_off=function(){return(a._audio_stream_append_off=a.asm.oa).apply(null,arguments)};
a._audio_generate_init=function(){return(a._audio_generate_init=a.asm.pa).apply(null,arguments)};a._audio_get_note_delay=function(){return(a._audio_get_note_delay=a.asm.qa).apply(null,arguments)};a._audio_set_note_delay=function(){return(a._audio_set_note_delay=a.asm.ra).apply(null,arguments)};a.AsciiToString=A;var W;O=function ha(){W||X();W||(O=ha)};
function X(){function b(){if(!W&&(W=!0,a.calledRun=!0,!y)){T(K);l(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();L.unshift(c)}T(L)}}if(!(0<M)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)ba();T(J);0<M||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}a.run=X;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();X();


  return ZetaNative.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = ZetaNative;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return ZetaNative; });
else if (typeof exports === 'object')
  exports["ZetaNative"] = ZetaNative;
